# Cloudflare zone records — domain-attach (DOMAIN-ONBOARDING-PLAYBOOK.md §2-4).
# Apply AFTER adding the zone + switching NS. Terraform optional (dashboard works
# too); this keeps the zone auditable. Requires: cloudflare provider + token.
#   terraform init && terraform plan && terraform apply

variable "zone_id" { type = string }
variable "domain" { type = string }
variable "vps_ip" { type = string }

resource "cloudflare_dns_record" "mail_a" {
  zone_id = var.zone_id
  name    = "mail"
  type    = "A"
  content = var.vps_ip
  proxied = false # MUST stay DNS-only (MX target)
}

resource "cloudflare_dns_record" "mail_mx" {
  zone_id  = var.zone_id
  name     = var.domain
  type     = "MX"
  content  = "mail.${var.domain}."
  priority = 10
}

resource "cloudflare_dns_record" "spf" {
  zone_id = var.zone_id
  name    = var.domain
  type    = "TXT"
  content = "v=spf1 mx include:senders.smtp2go.com ~all"
}

resource "cloudflare_dns_record" "dmarc" {
  zone_id = var.zone_id
  name    = "_dmarc"
  type    = "TXT"
  content = "v=DMARC1; p=none; rua=mailto:dmarc@${var.domain}; fo=1"
}

resource "cloudflare_dns_record" "mta_sts" {
  zone_id = var.zone_id
  name    = "_mta-sts"
  type    = "TXT"
  content = "v=STSv1; id=20260801"
}

resource "cloudflare_dns_record" "caa" {
  zone_id = var.zone_id
  name    = var.domain
  type    = "CAA"
  content = "0 issue \"letsencrypt.org\""
}

# DKIM per sender (values generated by Stalwart / Listmonk / Mautic)
resource "cloudflare_dns_record" "dkim_stalwart" {
  zone_id = var.zone_id
  name    = "mail._domainkey"
  type    = "TXT"
  content = "v=DKIM1; k=rsa; p=<STALWART_PUBLIC_KEY>"
}

resource "cloudflare_dns_record" "dkim_listmonk" {
  zone_id = var.zone_id
  name    = "default._domainkey"
  type    = "TXT"
  content = "v=DKIM1; k=rsa; p=<LISTMONK_PUBLIC_KEY>"
}

# VPS tool subdomains — DNS-only, public access ONLY via Cloudflare Tunnel
resource "cloudflare_dns_record" "tools" {
  for_each = toset(["mautic", "listmonk", "chatwoot", "umami", "kuma", "n8n"])
  zone_id  = var.zone_id
  name     = each.key
  type     = "A"
  content  = var.vps_ip
  proxied  = false
}